<#
DO NOT EDIT THIS FILE WHEN IT IS LOCATED AT THE DEFAULT c:\scripts\Exchange-Online-Email-Remediation\Exchange-online-Email-Remediation-Settings-Sample.ps1
You need to copy this template to c:\scripts\Exchange-online-Email-Remediation-Settings.ps1

#>
#Change to match your Office/Azure tenant 
$emaildomain = "@domain.com"
#Default look back in days the script uses; can be changed when running the script!
$defaultLookBack = "3"
